### ISSUE TITLE
FileAPI needs something like a fetchAllPublicProjects() method

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#97]
`FileAPI.fetchAllPersonalProjects()` returns different things, depending on whether user is logged in or not. This has ugly consequences for the Start Page: after logging in, the list of "public projects" is different. This doesn't make any sense.

Would it be better to have two separate calls, one for truly public projects, and a different call for personal (i.e. logged in) projects?

Because the way things are now, I can't get the list of public projects once I've logged in.

**Comment by billyc** [comment]
@Janekdererste FYI I was asked to pull the "Public Gallery" section off the front page today (before tomorrow's meeting) because projects which a client owns but ARE NOT PUBLIC are shown once they've logged in. He assumes this would sow panic and discontent; and he's probably right. 

So, until we get this fixed, there is no longer a "Public Gallery"'.

**Comment by Janekdererste** [comment]
fetchPersonalProjects is probably a misleading name. It fetches the projects for the current user which is either a logged in user or the 'public User'. There could be an additional method, which always fetches public projects.

**Comment by Janekdererste** [comment]
Never liked the word 'Public Gallery' anyway

**Comment by billyc** [comment]
Lol. Open to suggestions ;-)

**Comment by Janekdererste** [comment]
This was solved somewhere

**Comment by billyc** [comment]
@Janekdererste this is still not fixed!!

The list of public projects still changes depending on who you're logged in as (or anonymous).
